"""Renamed 'body' to 'comment' in Post model

Revision ID: 6b1134362500
Revises: 0085cedc5e74
Create Date: 2025-09-01 17:32:06.325378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b1134362500'
down_revision = '0085cedc5e74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment', sa.String(length=300), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('comment')

    # ### end Alembic commands ###
