"""Add category column to posts

Revision ID: 629395daf006
Revises: 874f0c178f04
Create Date: 2025-09-03 21:14:01.332358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '629395daf006'
down_revision = '874f0c178f04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###
