"""Renamed 'body' to 'comment'

Revision ID: 874f0c178f04
Revises: 6b1134362500
Create Date: 2025-09-01 17:37:20.889467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '874f0c178f04'
down_revision = '6b1134362500'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('body')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body', sa.VARCHAR(length=300), nullable=False))

    # ### end Alembic commands ###
